name: Build and publish

on:
  push:
    branches: "master"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        target: [ x86_64-unknown-linux-gnu ]

    steps:
    - uses: actions/checkout@v3
    - name: install deps
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
        wget git golang clang llvm curl pkg-config build-essential zlib1g-dev \
        gcc-multilib libc6-dev linux-libc-dev linux-headers-generic libbpf-dev

    - name: setup symlinks for cross-compilation
      run: |
        sudo ln -sf /usr/include/x86_64-linux-gnu/asm /usr/include/asm
        sudo ln -sf /usr/include/x86_64-linux-gnu/gnu /usr/include/gnu
        sudo ln -sf /usr/include/x86_64-linux-gnu/bits /usr/include/bits
        sudo ln -sf /usr/include/x86_64-linux-gnu/sys /usr/include/sys

    - name: setup build environment
      run: |
        echo "BPF_CLANG=clang" >> $GITHUB_ENV
        echo "BPF_CFLAGS=-O2 -g -Wall -Werror -target x86_64" >> $GITHUB_ENV


    - name: build package
      run:  make build

